let DATA={},META={},current="overview";
const LABELS={contacts:"CONTACTS",entities:"ENTITIES",locations:"LOCATIONS",artifacts:"ARTIFACTS",corporations:"CORPORATIONS",events:"EVENTS",documents:"DOCUMENTS"};
const content=document.querySelector("#content"),nav=document.querySelector("#nav"),search=document.querySelector("#search"),count=document.querySelector("#count"),breadcrumbs=document.querySelector("#breadcrumbs");
const bootLines=["Infomorph Loading","Authenticating Crewmember...","Crewmember Access Token Accepted","Datapad Link Established","LOADING FIELD INTELLIGENCE..."];
function runBoot(){const boot=document.querySelector("#boot"),target=document.querySelector("#bootLines");let i=0;function next(){if(i<bootLines.length){let line=document.createElement("div");line.textContent="> "+bootLines[i++];target.appendChild(line);setTimeout(next,180)}else setTimeout(()=>boot.classList.add("hidden"),350)}next()}
fetch("data/campaign.json").then(r=>r.json()).then(d=>{META=d.meta||{};DATA={...d};delete DATA.meta;document.querySelector("#node").textContent=META.node||"08-29";document.querySelector("#sync").textContent="LAST SYNC: "+(META.lastSync||"2026-08-29");document.querySelector("#build").textContent=META.build||"0.3";buildNav();overview();runBoot()}).catch(err=>{content.innerHTML=`<div class="error">DATABASE LOAD FAILURE // ${err.message}</div>`;document.querySelector("#boot").classList.add("hidden")});
function all(){return Object.entries(DATA).flatMap(([cat,a])=>a.map(x=>({...x,cat})))}
function setBreadcrumb(parts){breadcrumbs.innerHTML=parts.map((p,i)=>`<span class="${i===parts.length-1?"current":""}">${p}</span>${i===parts.length-1?"":"<em>›</em>"}`).join("")}
function stateBadge(label,type=""){return `<span class="badge ${type}">${label}</span>`}
function knowledgeClass(k){return k==="KNOWN"?"known":k==="PARTIAL"?"partial":k==="UNVERIFIED"?"unverified":k==="CLASSIFIED"?"classified":""}
function updateClass(s){return s==="NEW"?"new":s==="UPDATED"?"updated":s==="COMPROMISED"?"compromised":""}
function buildNav(){nav.innerHTML=`<button onclick="overview()">◈ OVERVIEW</button>`+Object.keys(DATA).map(c=>`<button onclick="category('${c}')">◈ ${LABELS[c]}</button>`).join("")}
function card(x){const u=x.updateState&&x.updateState!=="NONE"?stateBadge(x.updateState,updateClass(x.updateState)):"";return `<article class="card ${x.special==="monarch"?"monarch-card":""}" onclick="entry('${x.cat}','${x.id}')"><div class="meta">${x.recordId||x.tag} // ${x.cat.toUpperCase()}</div><h3>${x.name}</h3><div class="subtitle">${x.subtitle||""}</div><div class="card-badges">${stateBadge(x.knowledge||"UNKNOWN",knowledgeClass(x.knowledge))}${u}</div></article>`}
function overview(){current="overview";setBreadcrumb(["Datapad","OVERVIEW"]);document.querySelector("#title").textContent=META.campaignTitle||"FIELD CREW NETWORK";document.querySelector("#intro").textContent="The Crew's Ongoing Observations and Recordings.";count.textContent="";const recent=all().filter(x=>x.updateState&&x.updateState!=="NONE").sort((a,b)=>(b.updated||"").localeCompare(a.updated||""));content.innerHTML=`<div class="section">RECENT INTELLIGENCE</div><div class="recent-strip">${recent.length?recent.map(x=>`<article class="recent ${updateClass(x.updateState)}" onclick="entry('${x.cat}','${x.id}')"><div class="recent-state">${x.updateState}</div><div><strong>${x.name}</strong><small>${x.updated||"UNKNOWN"} // ${LABELS[x.cat]}</small></div></article>`).join(""):`<div class="muted">NO RECENT FIELD UPDATES</div>`}</div><div class="section">DATABASE INDEX</div><div class="grid">${Object.entries(DATA).map(([c,a])=>`<article class="card index-card" onclick="category('${c}')"><div class="meta">ARCHIVE</div><h3>${LABELS[c]}</h3><p>${a.length} indexed record(s).</p></article>`).join("")}</div>`}
function category(c){current=c;setBreadcrumb(["DATABASE",LABELS[c]]);document.querySelector("#title").textContent=LABELS[c];document.querySelector("#intro").textContent=`${DATA[c].length} indexed record(s). Select an entry to access the crew network.`;count.textContent=`${DATA[c].length} RECORDS`;content.innerHTML=`<div class="section">${LABELS[c]} // INDEX</div><div class="grid">${DATA[c].map(x=>({...x,cat:c})).map(card).join("")}</div>`}
function imageBlock(x){if(!x.image)return"";return `<div class="image-frame"><img src="${x.image}" alt="${x.name}" onerror="this.parentElement.classList.add('missing')"><div class="image-placeholder"><span>NO VISUAL RECORD</span><small>ADD IMAGE: ${x.image}</small></div><div class="image-scan"></div></div>`}
function entry(c,id){const x=DATA[c].find(y=>y.id===id);current=c;setBreadcrumb(["DATABASE",LABELS[c],x.name]);document.querySelector("#title").textContent=LABELS[c];document.querySelector("#intro").textContent="FIELD CREW NETWORK RECORD // AUTHORIZED ACCESS";count.textContent="RECORD OPEN";const facts=Object.entries(x.facts||{}).map(([k,v])=>`<div class="fact"><small>${k.replace(/([A-Z])/g," $1").toUpperCase()}</small>${Array.isArray(v)? `<ul>${v.map(item=>`<li>${item}</li>`).join("")}</ul>`: `<strong>${v}</strong>`}</div>`).join("");const extras=["voice","manner","wants","tip","canTalkAbout","notes"].filter(k=>x[k]).map(k=>`<div class="detail"><b>${k.replace(/([A-Z])/g," $1").toUpperCase()}</b>${Array.isArray(x[k])?`<ul>${x[k].map(v=>`<li>${v}</li>`).join("")}</ul>`:`<p>${x[k]}</p>`}</div>`).join("");const reds=(x.redactions||[]).map(t=>`<div class="redaction-line"><span class="redaction">${t}</span></div>`).join("");const links=(x.links||[]).map(id=>{const z=all().find(a=>a.id===id);return z?`<span class="link" onclick="entry('${z.cat}','${z.id}')">${z.name}</span>`:""}).join("");content.innerHTML=`<article class="entry ${x.special==="monarch"?"monarch-record":""}"><div class="record-topline"><span>${x.special==="monarch"?"SYSTEM AUTHORITY RECORD":"FIELD ARCHIVE RECORD"}</span><span>${x.recordId||"UNASSIGNED"}</span></div><div class="entryhead"><div><div class="meta">${x.status} // ${x.updated||"UNKNOWN"}</div><h2>${x.name}</h2><div class="entry-subtitle">${x.subtitle||""}</div></div><div class="entry-badges">${stateBadge(x.knowledge||"UNKNOWN",knowledgeClass(x.knowledge))}${x.updateState&&x.updateState!=="NONE"?stateBadge(x.updateState,updateClass(x.updateState)):""}</div></div><div class="record-layout"><div><div class="facts">${facts}</div><div class="integrity"><div class="integrity-row"><span>ARCHIVE INTEGRITY</span><b>${x.integrity??"?"}%</b></div><div class="integrity-track"><div class="integrity-fill ${x.integrity>100?"overflow":""}" style="width:${Math.min(x.integrity||0,100)}%"></div></div></div><div class="section">FIELD NOTES</div><p>${x.desc||""}</p>${reds}${extras}<div class="section">KNOWN ASSOCIATIONS</div><div class="links">${links||"<span class='muted'>NONE INDEXED</span>"}</div></div>${imageBlock(x)}</div></article>`}
function doSearch(q){q=q.toLowerCase().trim();if(!q){overview();return}const r=all().filter(x=>JSON.stringify(x).toLowerCase().includes(q));setBreadcrumb(["DATABASE","SEARCH"]);document.querySelector("#title").textContent="SEARCH RESULTS";document.querySelector("#intro").textContent=`${r.length} matching record(s).`;count.textContent=`${r.length} HITS`;content.innerHTML=`<div class="section">QUERY // ${q.toUpperCase()}</div><div class="grid">${r.map(card).join("")}</div>`}
search.oninput=e=>doSearch(e.target.value);
